name: notehub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shimmer: ^3.0.0
  open_file: ^3.5.9
  lottie: ^3.1.3
  intl: ^0.20.2
  toastification: ^3.0.3
  dio: ^5.7.0
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  file_picker: ^10.3.10
  cached_network_image: ^3.4.1
  liquid_pull_to_refresh: ^3.0.1
  flutter_local_notifications: ^20.1.0
  supabase_flutter: ^2.8.1
  glassmorphism: ^3.0.0
  flutter_image_compress: ^2.3.0
  url_launcher: ^6.3.0
  path: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/vectors/
